### ISSUE TITLE
rebuild_avatars scripts references deprecated NoArgsCommand

### ISSUE THREAD

**Issue by bctiemann** [grantmcconnaughey/django-avatar#142]
ImportError: cannot import name NoArgsCommand

https://github.com/django-extensions/django-extensions/issues/808

**Comment by grantmcconnaughey** [comment]
Hey @bctiemann. This issue was fixed in #141. It hasn't been deployed to PyPI yet. I'll try to get to that soon. In the meantime, install the dependency from GitHub if you need to run that command now.

**Comment by bctiemann** [comment]
Got it—thanks!

**Comment by Darkmatter81** [comment]
Has this fix been deployed yet? When I do a pip install I still get the bug, but I can see the fix on github. 

Cheers
